### ISSUE TITLE
Rename This Repo?

### ISSUE THREAD

**Issue by GrahamCampbell** [php-build/phpunit-plugin#3]
Should we rename this repo to plugin-phpunit or phpunit-plugin?

**Comment by GrahamCampbell** [comment]
Note that renames behave the same as transfers.

**Comment by CHH** [comment]
+1 for phpunit-plugin

**Comment by GrahamCampbell** [comment]
Shall I do this now then?

**Comment by GrahamCampbell** [comment]
Done.
